templateDir: ./sdk-resources/beta-resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-sdk
npmRepository: sailpoint.com
npmVersion: 1.2.0
useSingleRequestParameter: true
