name: Publish SDK package to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd sdk-output
          npm ci

      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./sdk-output/package.json
